
# main.py - two functions
#   Make group of research papers: clustering
#   (1) summerize each research papers (topic function)
#   (2)
#   (3)
#
#   Find most used comand from computer command "history"
#   (1) extract words in each command
#   (2) count them
#   (3) find most common word

# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

# COVID-19 Open Research Dataset Challenge (CORD-19)
# What has been published about information sharing and inter-sectoral collaboration?
#
# Cloud Cho in May 5, 2020
#
# How to run this code:
#   $ python main.py --choice most --in_file bash_history.txt
#
# Work?
#
# Error
#   some in "topic.py"
#
# To do
#    Inference with new document
#      How to use weight from LDA, LSI, NMF?
#      Abnormal - XGBoost, Encoder Decoder
#    Groupping the document
#
#    find data from Keggle
#
# Runtime environment
#    read_doc_py_3_8 Anaconda
#
#
# Reference:
#   Task: https://www.kaggle.com/allen-institute-for-ai/CORD-19-research-challenge/tasks?taskId=583

# You can write up to 5GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All"
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session


import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)


# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import argparse, os, pdb, sys
import string

# pyldavis required Python 3.8 for Anaconda
from sklearn.feature_extraction.text import CountVectorizer
from spacy.lang.en import English
from spacy.lang.en.stop_words import STOP_WORDS
import topic



EARLY_DEBUGGING = False
DEBUGGING = True
EARLY_TESTING = False
TESTING = True

# if summary already done (basically topic function)
#   This file will exist
# FILE = "/home/cloud/data/covid_19/metadata.csv"
# This is result of file reading function of this code
FILE = "/home/cloud/computer_programming/python/china_virus/read_doc/result/hrdata.csv"
KEGGLE_FOLDER = "/keggle/input"


def getting_arg():
    parser = argparse.ArgumentParser(description='Make data')
    parser.add_argument('--dataset', dest='dataset',
        default='/home/cloud/data/',
        help='dataset base folder location')
    parser.add_argument('--in_file', dest='in_file',
        help='input file name')
    parser.add_argument('--in_folder', dest='in_folder',
        help='input folder name')
    parser.add_argument('--out_file', dest='out_file',
        help='output file name')
    parser.add_argument('--choice', dest='choice', type=str,
        help='Function choice: \
        Catastropy, Smaller, Pattern, cluster, most')

    return parser


def clustering(args):

    # (1) Start chatbot
    # She will receive a question and digest it to process

    # (2) Input of each paper

    # Latent Semantic Indexing Model using Truncated SVD
    if (not os.path.exists(FILE)):
        par = {'iteration': 2, 'no of topic': 10}
        given_dir = "/home/cloud/data/covid_19"
        file_name = "metadata_small.csv"
        wines = os.path.join(given_dir, file_name)
        print("{} will be read".format(wines))
        topic.summarize_doc(wines, par)  # calling topic.py file

    # To do
    # where is the folder?
    elif (os.path.exists(KEGGLE_FOLDER)):
        print("{} will be read".format(KEGGLE_FOLDERV))
        for dirname, _, filenames in os.walk('/kaggle/input'):
            for filename in filenames:
                # print(os.path.join(dirname, filename))
                if (DEBUGGING):
                    pdb.set_trace()


    # (3) Make summary of paper
    # paper title | total page | summary
    else:
        # The FILE is already generated by this code
        print("{} will be read".format(FILE))
        df = pd.read_csv(FILE)
        pdb.set_trace()

    #
    # Comparing papers -> put in a table
    # Method 1
    #   Latent Semantic Indexing Model using Truncated SVD --> Longest common
    #   subsequence problem or Longest common substring problem
    #
    # Method 2
    #   Keyword matching --> Latent Semantic Indexing Model using Truncated SVD -->
    #   Longest common subsequence problem or Longest common substring problem
    #
    # papser name | similar | not similar
    #   similarity by keyword matching count?

    # (4) Receive question
    # Make list of synomym of key word
    #   How chatbot understand question?


    # (5) Find document using summary
    # Check paper title
    # Check summary
    #   Yes: read document
    #   No:


    # (6) Read document to answer the question
    #   How chatbot answer?


def most_command(args):
    parser = English()
    punctuations = string.punctuation
    stopwords = list(STOP_WORDS)
    wines = dict()
    count_empty_title = 0

    vectorizer = CountVectorizer(min_df=5, max_df=0.9,
        stop_words='english',
        lowercase=True, token_pattern='[a-zA-Z\-][a-zA-Z\-]{2,}')

    with open(args.in_file, 'r') as f_in:
        for idx, line in enumerate(f_in):
            try:
                wines["history"][idx], _ = topic.spacy_tokenizer(parser,
                    line, stopwords,
                    punctuations, count_empty_title)
            except Exception as e:
                print (e.args)

        pdb.set_trace()

        # Convert a collection of text documents to a matrix of token counts
        # To Do
        #    convert "_io.TextIOWrapper" to
        data_vectorized = vectorizer.fit_transform(f_in)


def main(args):
    if (args.choice == 'cluster'):
        clustering(args)
    elif (args.choice == 'most'):
        most_command(args)
    else:
        print("Unknown")



if __name__ == '__main__':
    args = getting_arg().parse_args()
    main(args)
